### ISSUE TITLE
error with ghost

### ISSUE THREAD

**Issue by NicolaDM** [walkergussler/quentin#1]
Hi, I am trying to use this script, but I get the error

```
Traceback (most recent call last):
  File ".../quentin.py", line 20, in <module>
    from ghost.util.distance import hamming
ImportError: No module named util.distance
```

Looking at the script, it says:
"Should be inside ghost virtual environment or else youll get errors"
What does it mean?

Best wishes

**Comment by walkergussler** [comment]
I am sorry for replying to this so slowly, I am rather new to github, and I was not aware of this comments section! I will develop a version that does not require access to the GHOST system

**Comment by walkergussler** [comment]
OK there is a new version called no_ghost_quentin, would you see if you can run it without any error? If you find any, please paste the traceback here and I will respond more promptly than last time

**Comment by walkergussler** [comment]
I have moved this code base to a new address, please download that and try it instead, it is build to work better for naiive users. Thank you!
