### ISSUE TITLE
lsqlin module not found 

### ISSUE THREAD

**Issue by rekm** [walkergussler/quentin#2]
lsqlin seems to have been deleted in commit 
Mar 21st 2018  962433d9e9dee5de950e0f9e4a7480fc74b7f614. 
quentin.py is still importing the non existent  module.

**Comment by walkergussler** [comment]
I'm sorry for the delayed response. I have changed some things around to make this software more accessible to new users. Please try to run the software with the current repo and let me know how it goes!

**Comment by walkergussler** [comment]
I have moved this code base to [a new address](https://github.com/walkergussler/inscape) , please download that and try it instead, it is build to work better for naiive users. Thank you!
